# Generated by Django 3.0.1 on 2019-12-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=100)),
                ('tutorial_content', models.TextField()),
                ('published_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
