# Generated by Django 3.0.1 on 2019-12-26 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 26, 16, 18, 21, 416869), verbose_name='date published'),
        ),
    ]
