# Generated by Django 3.0.1 on 2019-12-30 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191230_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='tutorial_Category',
            new_name='tutorial_category',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 19, 35, 14, 187266), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_title',
            field=models.CharField(max_length=200),
        ),
    ]
